version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: liftlog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - liftlog-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - liftlog-network

  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: adminpass
      INFLUXDB_ORG: liftlog_org
      INFLUXDB_BUCKET: workout_data
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    networks:
      - liftlog-network

volumes:
  db-data:
  influxdb-data:

networks:
  liftlog-network:
    driver: bridge
